{
  "path": "/documentation/foundation/urlerror/backgroundtaskcancelledreason",
  "type": "Enumeration",
  "name": "URLError.BackgroundTaskCancelledReason",
  "desc": "An enumeration of reasons used to explain the cancellation of a background task.",
  "items": [
    {
      "name": "init?(rawValue: Int)",
      "desc": "Creates a background cancellation reason from the provided raw value."
    },
    {
      "name": "case backgroundUpdatesDisabled",
      "desc": "A reason that indicates the system canceled the background task because background tasks are disabled."
    },
    {
      "name": "case insufficientSystemResources",
      "desc": "A reason that indicates the system canceled the background task because it lacks sufficient resources to perform the task."
    },
    {
      "name": "case userForceQuitApplication",
      "desc": "A reason that indicates the system canceled the background task because the user force-quit the application."
    },
    {
      "name": "var hashValue: Int",
      "desc": "The hash value."
    },
    {
      "name": "func hash(into: inout Hasher)",
      "desc": "Hashes the essential components of this value by feeding them into the given hasher."
    },
    {
      "name": "var rawValue: Int",
      "desc": "The raw value of this background cancellation reason instance."
    },
    {
      "name": "typealias URLError.BackgroundTaskCancelledReason.RawValue",
      "desc": "The type of the raw value."
    },
    {
      "name": "static func != (URLError.BackgroundTaskCancelledReason, URLError.BackgroundTaskCancelledReason) -> Bool",
      "desc": "Returns a Boolean value that indicates whether two values are unequal."
    }
  ],
  "declaration": "enum BackgroundTaskCancelledReason : Int"
}