{
  "path": "/documentation/cfnetwork/cfnetworkerrors/cfurlerrorcallisactive",
  "type": "Enumeration Case",
  "name": "CFNetworkErrors.cfurlErrorCallIsActive",
  "desc": "The connection failed because a call is active.",
  "items": [],
  "declaration": "case cfurlErrorCallIsActive = -1019"
}