{
  "path": "/documentation/corefoundation/cfurlenumeratorresult/error",
  "type": "Enumeration Case",
  "name": "CFURLEnumeratorResult.error",
  "desc": "An error occurred during enumeration. The error parameter of the function is populated with error information.",
  "items": [],
  "declaration": "case error = 3"
}