{
  "path": "/documentation/foundation/macherror/2292949-exceptionprotected",
  "type": "Type Property",
  "name": "exceptionProtected",
  "desc": "An attempt was made to fetch an exception port that is protected, or to abort a thread while processing a protected exception.",
  "items": [],
  "declaration": "static var exceptionProtected: MachError.Code { get }"
}