{
  "path": "/documentation/accelerate/quadrature/error",
  "type": "Enumeration",
  "name": "Quadrature.Error",
  "desc": "Errors thrown by the Quadrature structure.",
  "items": [
    {
      "name": "case badIntegrandBehaviour"
    },
    {
      "name": "case generic"
    },
    {
      "name": "case integrateMaxEval"
    },
    {
      "name": "case `internal`"
    },
    {
      "name": "case invalidArgument"
    },
    {
      "name": "init(quadratureStatus: quadrature_status)"
    },
    {
      "name": "var errorDescription: String"
    },
    {
      "name": "var hashValue: Int"
    },
    {
      "name": "var localizedDescription: String"
    },
    {
      "name": "func hash(into: inout Hasher)"
    },
    {
      "name": "static func != (Quadrature.Error, Quadrature.Error) -> Bool"
    },
    {
      "name": "static func == (Quadrature.Error, Quadrature.Error) -> Bool"
    }
  ],
  "declaration": "enum Quadrature.Error",
  "conformsTo": [
    "Error"
  ]
}