{
  "path": "/documentation/networkextension/neappproxyflowerror/code",
  "type": "Enumeration",
  "name": "NEAppProxyFlowError.Code",
  "desc": "No overview available.",
  "items": [
    {
      "name": "case notConnected",
      "desc": "The flow is not fully opened."
    },
    {
      "name": "case peerReset",
      "desc": "The flow was closed by the remote peer of the flow."
    },
    {
      "name": "case hostUnreachable",
      "desc": "The remote endpoint of the flow could not be reached."
    },
    {
      "name": "case invalidArgument",
      "desc": "An invalid argument was passed to a NEAppProxyFlow method."
    },
    {
      "name": "case aborted",
      "desc": "The flow was aborted."
    },
    {
      "name": "case refused",
      "desc": "The flow could not be connected to its remote endpoint."
    },
    {
      "name": "case timedOut",
      "desc": "The flow timed out."
    },
    {
      "name": "case `internal`",
      "desc": "An internal error was encountered while handling the flow."
    },
    {
      "name": "case datagramTooLarge"
    },
    {
      "name": "case readAlreadyPending"
    }
  ],
  "declaration": "enum NEAppProxyFlowError.Code : Int, _ErrorCodeProtocol, @unchecked Sendable",
  "conformsTo": [
    "Sendable"
  ]
}